# Generated by Django 3.2 on 2021-12-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='media/product_image/Adidas-hoodie.png', upload_to='product_image'),
        ),
    ]
